export const SET_PROFILE = 'set_profile'
export const SET_AUTH = 'set_auth'
export const SET_PAYMENT_ACCOUNT_NUMBER = 'set_payment_account_number'
export const SET_BANK_TYPES = 'set_bank_type'
export const SET_TRANSFER_METHODS = 'set_transfer_method'